/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package h.ibrahim.com;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.JDBCType;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.oracore.OracleType;
import static oracle.sql.DATE.getCurrentDate;
/**
 *
 * @author hibra
 */
public class KullanıcıKaydı extends javax.swing.JFrame {
Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement stmt =null;
    /**
     * Creates new form KullanıcıKaydı
     */
    public KullanıcıKaydı() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void baglan()throws ClassNotFoundException, SQLException
    {
        //veritabanının bağlantı 
        Class.forName("oracle.jdbc.driver.OracleDriver");
       conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "GAZI", "123456");
    }
    public boolean bosmu(){
        if(tfTC.getText().length()<1){
            return false;
            
        }else if(tfKullanıcıAdı.getText().length()<1){
            return false;
        }else if(tfisim.getText().length()<1){
            return false;
        }else if(tfAnahtar.getText().length()<1){
            return false;
        }else if(tfsoyİsim.getText().length()<1){
            return false;
        }else if(jpSifre.getText().length()<1){
            return false;
        }else if(jpSifreTekrar.getText().length()<1){
            return false;
        }else if(jcSec.getSelectedItem().equals("SEÇİNİZ!")){
            return false;
        }
        return true;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        tfTC = new javax.swing.JTextField();
        b = new javax.swing.JLabel();
        tfisim = new javax.swing.JTextField();
        c = new javax.swing.JLabel();
        tfsoyİsim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcSec = new javax.swing.JComboBox<>();
        d = new javax.swing.JLabel();
        tfKullanıcıAdı = new javax.swing.JTextField();
        e = new javax.swing.JLabel();
        jpSifre = new javax.swing.JPasswordField();
        e1 = new javax.swing.JLabel();
        jpSifreTekrar = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAnahtar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("KAYIT EKRANI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 274, 37));

        a.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("TC. KİMLİK NUMARASI:");
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        tfTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTCActionPerformed(evt);
            }
        });
        getContentPane().add(tfTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 134, -1));

        b.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setText("İSİM                      :");
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));
        getContentPane().add(tfisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 134, -1));

        c.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setText("SOYİSİM                 :");
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 160, -1));
        getContentPane().add(tfsoyİsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 134, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SİGORTA TÜRÜ         :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, -1));

        jcSec.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jcSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ!", "SSK", "BAĞKUR", "EMEKLİ SANDIĞI", "SGK" }));
        getContentPane().add(jcSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 134, -1));

        d.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        d.setForeground(new java.awt.Color(255, 255, 255));
        d.setText("KULLANICI ADI        :");
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 150, -1));
        getContentPane().add(tfKullanıcıAdı, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 134, -1));

        e.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        e.setForeground(new java.awt.Color(255, 255, 255));
        e.setText("ŞİFRE                    :");
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 150, -1));
        getContentPane().add(jpSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 134, -1));

        e1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 255, 255));
        e1.setText("ŞİFRE TEKRAR         :");
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 150, -1));
        getContentPane().add(jpSifreTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 134, -1));

        jButton1.setBackground(new java.awt.Color(255, 112, 1));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setText("KAYDOL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 134, -1));

        jButton2.setBackground(new java.awt.Color(239, 132, 2));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("TEMİZLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 134, -1));

        jButton3.setBackground(new java.awt.Color(255, 174, 3));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton3.setText("KULLANICI GİRİŞİ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 210, 57));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("ŞİFRENİZİ KİMSE İLE PAYLAŞMAYINIZ!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 308, 14));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h/ibrahim/com/index.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 303, 271));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h/ibrahim/com/atatürk.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 540, 150));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ANAHTAR KELİME    :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 160, -1));
        getContentPane().add(tfAnahtar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     KullanıcıGirişi n1=new KullanıcıGirişi();
      n1.setVisible(true);
          this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
          baglan();
          if(!(jpSifre.getText().equals(jpSifreTekrar.getText()))){
               JOptionPane.showMessageDialog(tfTC, "ŞİFRE TEKRARANIZ UYUŞMADI!");
           }else if(!(bosmu())){
                JOptionPane.showMessageDialog(rootPane, "LÜTFEN BOŞ ALANLARI DOLDURUNUZ!");
           
           }
          else if(tfTC.getText().length()==11){
          CallableStatement sta = conn.prepareCall("{CALL HASTANERANDEVU.SP_KULLANICIKAYDI(?,?,?,?,?,?,?)}");      
          
          
          sta.setString(1, tfTC.getText());
          
          sta.setString(2, tfisim.getText()); 
          
          sta.setString(3, tfsoyİsim.getText()); 
          
          sta.setString(4, (String) jcSec.getSelectedItem()); 
          
          sta.setString(5, tfKullanıcıAdı.getText());
          
          sta.setString(6, jpSifre.getText()); 
          
          sta.setString(7, tfAnahtar.getText());
          
          
          sta.executeUpdate();
          
            JOptionPane.showMessageDialog(rootPane,"KAYIT İŞLEMİ BAŞARILI!");
           
            conn.close();
          
          }else{
               JOptionPane.showMessageDialog(tfTC, "T.C kimlik numaranız 11 hane giriniz!");
           }
      }catch(Exception ex)
        {
           JOptionPane.showMessageDialog(tfTC, "SİSTEME İKİ DEFA KAYIT YAPTIRMAZSINIZ!");
            Logger.getLogger(KullanıcıKaydı.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       tfKullanıcıAdı.setText("");
       jpSifre.setText("");
       tfisim.setText("");
       tfsoyİsim.setText("");
       tfTC.setText("");
       jpSifreTekrar.setText("");
       jcSec.setSelectedIndex(0);
       tfAnahtar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıKaydı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel e1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcSec;
    private javax.swing.JPasswordField jpSifre;
    private javax.swing.JPasswordField jpSifreTekrar;
    private javax.swing.JTextField tfAnahtar;
    private javax.swing.JTextField tfKullanıcıAdı;
    private javax.swing.JTextField tfTC;
    private javax.swing.JTextField tfisim;
    private javax.swing.JTextField tfsoyİsim;
    // End of variables declaration//GEN-END:variables
}
