/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package h.ibrahim.com;


import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author hibra
 */
public class RandevuAL extends javax.swing.JFrame {
Connection conn=null;
    //ResultSet rs=null;
    PreparedStatement pst=null;
    Statement stmt1=null;
     Statement stmt=null;
     KullanıcıGirişi giriş =new KullanıcıGirişi();
    /**
     * Creates new form RandevuAL
     */
    public RandevuAL() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void baglan()throws ClassNotFoundException, SQLException
    {
        //veritabanının bağlantı 
        Class.forName("oracle.jdbc.driver.OracleDriver");
       conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "GAZI", "123456");
    }
    public boolean bosmu(){
        
            
        if(tfRandevuZamanı.getText().length()<18){
            return false;
        
            }else if(combo1.getSelectedItem().equals("Şehir")){
                return false;
            }else if(combo2.getSelectedItem().equals(null)){
                return false;
            }else if(combo3.getSelectedItem().equals(null)){
                return false;
            }else if(combo4.getSelectedItem().equals(null)){
                return false;
            }
        return true;
    }
    public void combox2()
        {
         //combo2.removeAllItems();
         
      try
        {
            try {
                baglan();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "VERİ TABANINA BAĞLANILAMADI!");
                Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE, null, ex);
            }
        CallableStatement sta = conn.prepareCall("{CALL HASTANERANDEVU.SP_HASTANEEKLE(?,?)}");      
        String sehir =(String) combo1.getSelectedItem();
        sta.setString(1, sehir);  
        
        sta.registerOutParameter(2,  OracleTypes.CURSOR);
        
        sta.executeQuery();
        ResultSet rs=(ResultSet) sta.getObject(2);
         
         while(rs.next()){
         String gelendeger = rs.getString("HASTANEADI");
         
         combo2.addItem(gelendeger);
              
          }         
         
         rs.close();
         conn.close();
        
        
        
        }
        catch (SQLException ex)
        {
            Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE,null,ex);
        JOptionPane.showMessageDialog(null,"HATA");
        }
        }
    
     public void listeleme()
     {
         //combo3.removeAllItems();
         
        try
        {
            try {
                baglan();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "VERİ TABANINA BAĞLANILAMADI!");
                Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE, null, ex);
            }
        CallableStatement sta = conn.prepareCall("{CALL HASTANERANDEVU.SP_SERVISEKLEME(?,?)}");      
        String hastane=combo2.getSelectedItem().toString();
        sta.setString(1, hastane);
        sta.registerOutParameter(2, OracleTypes.CURSOR);
        sta.executeQuery();
        ResultSet rs= (ResultSet) sta.getObject(2);
            while (rs.next()) {
               
                combo3.addItem(rs.getString("SERVISADI"));
               
                 }
        
         rs.close(); 
         conn.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE,null,ex);
        JOptionPane.showMessageDialog(null,"HATA");
        }
       }
    
     public void listeleme2()
     {
         //combo4.removeAllItems();
       
        
        
      try
        {
            try {
                baglan();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "VERİ TABANINA BAĞLANILAMADI!");
                Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE, null, ex);
            }
        String sehir = combo1.getSelectedItem().toString();
        String hastane=combo2.getSelectedItem().toString();
        String Servis=combo3.getSelectedItem().toString();
        CallableStatement sta = conn.prepareCall("{CALL HASTANERANDEVU.SP_DOKTOREKLEME(?,?,?,?)}");      
        
        sta.registerOutParameter(4, OracleTypes.CURSOR);
        
        sta.setString(1, hastane);
        sta.setString(2, Servis);
        sta.setString(3, sehir);
        sta.executeQuery();
        ResultSet rs= (ResultSet) sta.getObject(4);
        while (rs.next()) {
        /*if(Servis.equalsIgnoreCase(rs.getString("SERVISADI"))&&hastane.equalsIgnoreCase(rs.getString("HASTANEADI"))
                && sehir.equalsIgnoreCase(rs.getString("SEHIR")))*/
          combo4.addItem(rs.getString("DOKTORADI").toString());
             
                  } 
        
          
         rs.close();
         conn.close();
            
       }
        
        catch (SQLException ex)
        {
            
            Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE,null,ex);
        JOptionPane.showConfirmDialog(null,"HATA");
        
        }   
     }
 
      public void randevuekleyen(String hastaneno, String servisno, String doktorsıcıl, String tc){
       
      
            try
        {
            try {
                baglan();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "VERİ TABANINA BAĞLANILAMADI!");
                Logger.getLogger(RandevuAL.class.getName()).log(Level.SEVERE, null, ex);
            }
          
          CallableStatement sta2 = conn.prepareCall("{CALL HASTANERANDEVU.SP_RANDEVUEKLEME(?,?,?,?,?,?)}");      
          
          
          sta2.setString(1, tc);
       
          sta2.setString(2, (String) combo1.getSelectedItem()); 
          
          sta2.setString(3, hastaneno);
          
          sta2.setString(4, servisno); 
          
          sta2.setString(5, doktorsıcıl);
          
          sta2.setString(6, tfRandevuZamanı.getText());
         
          sta2.executeUpdate(); 
         
          JOptionPane.showMessageDialog(rootPane, "RANDEVU ALMA İŞLEMİ BAŞARILI!");
            randevunogetıren(tc, doktorsıcıl);
         conn.close();
    
        
        } catch (SQLException ex)
        {
            ex.printStackTrace();
       
        }
         
     }
      public void randevunogetıren(String tc, String doktorsıcıl){
          try {
              CallableStatement sta2 = conn.prepareCall("{CALL HASTANERANDEVU.SP_RANDEVUNOGETIR(?,?,?)}");      
          
               sta2.setString(1, tc);
               sta2.setString(2, doktorsıcıl);
               sta2.registerOutParameter(3, Ora,,,,,,,,,,,,,,,,,,,,,,,,,cleTypes.CURSOR);
          
               sta2.executeQuery();
          
            ResultSet rs= (ResultSet) sta2.getObject(3);
           String randevuno=null;
           
            while (rs.next()) {
                 randevuno = rs.getString("RANDEVUNO");
                 
            }
            
            JOptionPane.showMessageDialog(rootPane,"RANDEVU NUMARANIZ = "+ randevuno);
          
          }catch (SQLException ex) {
              ex.printStackTrace();
          }
              
          
      }
     
     
         @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfRandevuZamanı = new javax.swing.JTextField();
        combo2 = new javax.swing.JComboBox<>();
        combo3 = new javax.swing.JComboBox<>();
        combo4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1000, 10000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("MERKEZİ HASTANE RANDEVU ALMA EKRANI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 571, 54));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ŞEHİR SEÇİNİZ        :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 20));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HASTANE ADI          :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 150, 20));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SERVİS                  :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, 20));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DOKTOR SEÇİNİZ      :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 20));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RANDEVU ZAMANI    :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 150, 20));

        tfRandevuZamanı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRandevuZamanıActionPerformed(evt);
            }
        });
        getContentPane().add(tfRandevuZamanı, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 162, -1));

        combo2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        combo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo2İtemStateChanged(evt);
            }
        });
        combo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo2MouseClicked(evt);
            }
        });
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 160, -1));

        combo3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        combo3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo3İtemStateChanged(evt);
            }
        });
        combo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo3MouseClicked(evt);
            }
        });
        combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3ActionPerformed(evt);
            }
        });
        getContentPane().add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 160, -1));

        combo4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        getContentPane().add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 160, -1));

        jButton1.setBackground(new java.awt.Color(96, 232, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setText("RANDEVU AL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 170, 50));

        jButton2.setBackground(new java.awt.Color(182, 255, 4));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setText("TEMİZLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 140, 50));

        jButton3.setBackground(new java.awt.Color(31, 255, 0));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton3.setText("ANA MENÜ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 170, 40));

        combo1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Şehir", "ANKARA", "KIRIKKALE" }));
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1İtemStateChanged(evt);
            }
        });
        combo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo1MouseClicked(evt);
            }
        });
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 160, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("**YIL-AY-GÜN SAAT-DAKİKA(2017-12-12 14:15:00)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -140, 290, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h/ibrahim/com/appointment_icon.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 500, 460));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("**2018-12-25 14:15:00**");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 190, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h/ibrahim/com/atatürk.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 380, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRandevuZamanıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRandevuZamanıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRandevuZamanıActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      RandevuMenü e1=new RandevuMenü();
      e1.setVisible(true);
      this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        combo3.removeAllItems();
        listeleme();
    }//GEN-LAST:event_combo2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       tfRandevuZamanı.setText("");
       
       combo1.setSelectedIndex(0);
       combo2.setSelectedItem(null);
       combo3.setSelectedIndex(0);
       combo4.setSelectedItem(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combo1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1İtemStateChanged
      
    }//GEN-LAST:event_combo1İtemStateChanged

    private void combo3İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo3İtemStateChanged
      
       
    }//GEN-LAST:event_combo3İtemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
      
       try{
          baglan();
            if(!(bosmu())){
              JOptionPane.showMessageDialog(rootPane, "LÜTFEN BOŞ ALANLARI DOLDURUNUZ!");
            }
         
            else{
            //  if(eski()){
         String hastaneno = null;
         String servisno=null;
         String doktorsıcıl=null;
         String tc=null;
         
                  
             
         CallableStatement sta = conn.prepareCall("{CALL HASTANERANDEVU.SP_RANDEVU(?,?,?,?,?,?)}");      
          
          sta.setString(1, combo1.getSelectedItem().toString()); //şehir
          
          sta.setString(2, combo2.getSelectedItem().toString());  //hastaneadı
          
          sta.setString(3, combo3.getSelectedItem().toString());  //servis
          
          sta.setString(4,combo4.getSelectedItem().toString());  //doktoradı
          
          sta.setString(5, tfRandevuZamanı.getText()); //tarih
          
          
          
          
          
          sta.registerOutParameter(6, OracleTypes.CURSOR);
          
          sta.executeQuery();
          
          ResultSet rs= (ResultSet) sta.getObject(6);
            while (rs.next()) {
          tc =rs.getString("TC");
          hastaneno=rs.getString("HASTANENO");
          servisno=rs.getString("SERVISNO");
          doktorsıcıl=rs.getString("DOKTORSICIL");
          
                  }
  
         
        
         randevuekleyen(hastaneno,servisno,doktorsıcıl, tc );
         
           
          //}else{
           //   JOptionPane.showMessageDialog(rootPane, "SISTEM ŞU ANDA HİZMET VEREMİYOR!");
           //}
          }  
           conn.close();
      }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "VERİ TABANI HATASI!");
            Logger.getLogger(KullanıcıKaydı.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo2İtemStateChanged
     
    }//GEN-LAST:event_combo2İtemStateChanged

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
    combo2.removeAllItems();
          combox2();
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo2MouseClicked
       
        
    }//GEN-LAST:event_combo2MouseClicked

    private void combo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo1MouseClicked
     
    }//GEN-LAST:event_combo1MouseClicked

    private void combo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo3MouseClicked
        
    }//GEN-LAST:event_combo3MouseClicked

    private void combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3ActionPerformed
       combo4.removeAllItems();
        listeleme2();
    }//GEN-LAST:event_combo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandevuAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandevuAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandevuAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandevuAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandevuAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfRandevuZamanı;
    // End of variables declaration//GEN-END:variables

   
}
